export const listUsers = [
  {
    name: "Diego Eduardo",
    lastName: "Soliz Taurus",
    photo:
      "https://www.soyhenry.com/_next/image?url=%2Ftestimonials%2FAR%2Fdiegobarrios.webp&w=384&q=75",
    aboutMe:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit eros himenaeos inceptos sollicitudin magnis, nec nisi ad eget sociosqu tincidunt quam interdum massa vitae odio, torquent et phasellus netus velit dictum elementum libero pellentesque sagittis hac.",
    phone: "71650223",
  },
  {
    name: "Tatiana",
    lastName: "Flores Lopez",
    photo:
      "https://www.soyhenry.com/_next/image?url=%2Ftestimonials%2FMX%2Fabigailcortes.webp&w=384&q=75",
    aboutMe:
      "Lorem ipsum dolor sit amet consectetur adipiscing elit eros himenaeos inceptos sollicitudin magnis, nec nisi ad eget sociosqu tincidunt quam interdum massa vitae odio, torquent et phasellus netus velit dictum elementum libero pellentesque sagittis hac.",
    phone: "68550504",
  },
];

export const listContacts = [
  {
    idContact: "1",
    name: "Carlos",
    lastName: "Pérez Gutiérrez",
    phone: 71234567,
    email: "carlos.perez@example.com",
    date: "2023-01-15",
  },
  {
    idContact: "2",
    name: "Ana",
    lastName: "Gómez Salinas",
    phone: 78901234,
    email: "ana.gomez@example.com",
    date: "2023-02-20",
  },
  {
    idContact: "3",
    name: "Luis",
    lastName: "Martínez Rojas",
    phone: 74561238,
    email: "luis.martinez@example.com",
    date: "2023-03-05",
  },
  {
    idContact: "4",
    name: "María",
    lastName: "López Rivera",
    phone: 75891234,
    email: "maria.lopez@example.com",
    date: "2023-04-12",
  },
  {
    idContact: "5",
    name: "José",
    lastName: "Rodríguez Pérez",
    phone: 76458901,
    email: "jose.rodriguez@example.com",
    date: "2023-05-01",
  },
  {
    idContact: "6",
    name: "Lucía",
    lastName: "Fernández Castro",
    phone: 72109876,
    email: "lucia.fernandez@example.com",
    date: "2023-06-18",
  },
  {
    idContact: "7",
    name: "Pedro",
    lastName: "Ramírez Vargas",
    phone: 73456789,
    email: "pedro.ramirez@example.com",
    date: "2023-07-10",
  },
  {
    idContact: "8",
    name: "Claudia",
    lastName: "Torres Molina",
    phone: 75987654,
    email: "claudia.torres@example.com",
    date: "2023-08-22",
  },
  {
    idContact: "9",
    name: "Miguel",
    lastName: "Vargas Salazar",
    phone: 76543210,
    email: "miguel.vargas@example.com",
    date: "2023-09-30",
  },
  {
    idContact: "10",
    name: "Sofía",
    lastName: "Castro Álvarez",
    phone: 72345678,
    email: "sofia.castro@example.com",
    date: "2023-10-15",
  },
  {
    idContact: "11",
    name: "Andrés",
    lastName: "Mendoza Aguirre",
    phone: 73124567,
    email: "andres.mendoza@example.com",
    date: "2023-11-03",
  },
  {
    idContact: "12",
    name: "Valeria",
    lastName: "Silva Ramírez",
    phone: 74455678,
    email: "valeria.silva@example.com",
    date: "2023-12-25",
  },
  {
    idContact: "13",
    name: "Jorge",
    lastName: "Herrera Guzmán",
    phone: 75678901,
    email: "jorge.herrera@example.com",
    date: "2024-01-09",
  },
  {
    idContact: "14",
    name: "Camila",
    lastName: "Reyes Ortiz",
    phone: 76901234,
    email: "camila.reyes@example.com",
    date: "2024-02-14",
  },
  {
    idContact: "15",
    name: "Diego",
    lastName: "Cruz Muñoz",
    phone: 78765432,
    email: "diego.cruz@example.com",
    date: "2024-03-23",
  },
  {
    idContact: "16",
    name: "Isabel",
    lastName: "Morales Peña",
    phone: 79012345,
    email: "isabel.morales@example.com",
    date: "2024-04-05",
  },
  {
    idContact: "17",
    name: "Sebastián",
    lastName: "Ortiz Campos",
    phone: 79987654,
    email: "sebastian.ortiz@example.com",
    date: "2024-05-18",
  },
  {
    idContact: "18",
    name: "Paula",
    lastName: "Guerrero Navarro",
    phone: 74321098,
    email: "paula.guerrero@example.com",
    date: "2024-06-30",
  },
  {
    idContact: "19",
    name: "Tomás",
    lastName: "Chávez Lozano",
    phone: 73219876,
    email: "tomas.chavez@example.com",
    date: "2024-07-22",
  },
  {
    idContact: "20",
    name: "Fernanda",
    lastName: "Ríos Calderón",
    phone: 76519876,
    email: "fernanda.rios@example.com",
    date: "2024-08-11",
  },
  {
    idContact: "21",
    name: "Ricardo",
    lastName: "Peña Cabrera",
    phone: 74123456,
    email: "ricardo.pena@example.com",
    date: "2024-09-19",
  },
  {
    idContact: "22",
    name: "Gabriela",
    lastName: "Molina Flores",
    phone: 75781234,
    email: "gabriela.molina@example.com",
    date: "2024-10-27",
  },
  {
    idContact: "23",
    name: "Mateo",
    lastName: "Ibarra León",
    phone: 73569874,
    email: "mateo.ibarra@example.com",
    date: "2024-11-08",
  },
  {
    idContact: "24",
    name: "Daniela",
    lastName: "Ramos Quispe",
    phone: 76432890,
    email: "daniela.ramos@example.com",
    date: "2024-12-15",
  },
  {
    idContact: "25",
    name: "Alejandro",
    lastName: "Salazar Méndez",
    phone: 72098765,
    email: "alejandro.salazar@example.com",
    date: "2025-01-03",
  },
];
